### PR TITLE
Import path helper

### PR DESCRIPTION
**Pull request by danielsdeleo**
Built upon https://github.com/chef/chef-config/pull/7

This imports the `PathHelper` class from Chef into ChefConfig. In order to get it to work, I also needed to add the `windows?` method, so this patch fixes both #2 and #3.

These two things were a little tricky:

* PathHelper used `Chef::Log`, so I had to add a logger. By default it'll use a null logger. In Chef we can do `ChefConfig.logger = Chef::Log` and it should work like before.
* PathHelper used to raise `Chef::Exceptions::ValidationFailed`. This exception is used for a lot of different things in Chef, so I didn't think it made sense to move it into ChefConfig. I looked at the few places using PathHelper in Chef, and none of them are rescuing that error, so I think it should be okay to change it.

When we adopt this component as the default config for chef-client, we'll need to use the same "class alias" trick that we're gonna use for `Chef::Config`, e.g.,

```ruby
class Chef
  module Util
    PathHelper = ChefConfig::PathHelper
  end
end
```

@chef/client-core

### CODE REVIEW

**Comment by jdmundrawala** [comment]
:+1: we should enable appveyor as well

**Comment by danielsdeleo** [comment]
@jdmundrawala can you set that up?

**Comment by jdmundrawala** [comment]
yep

**Comment by danielsdeleo** [comment]
@jdmundrawala actually I think the plan is to move this code into the chef repo (it'll just be a separate directory) at which point we'll delete this repo. If we do that we won't need appveyor.

**Comment by smurawski** [comment]
:+1:  and :+1:  to @jdmundrawala setting up appveyor if this stays here.

**Comment by thommay** [comment]
:checkered_flag: :+1:

**Comment by lamont-granquist** [comment]
Kind of smells like we need a chef-utils gem to move pathhelper into or something like that...

**Pull request merged**
