### PR TITLE
use mixlib-shellout directly

### LINKED ISSUE #4: Fix dep on Chef::Mixin::ShellOut
As used here: https://github.com/chef/chef-config/blob/beeabc1f6cb1966e18cb4bd23ed66eca6f5aff14/lib/chef-config/config.rb#L688

That's the only place it is used. We could have Chef reopen the class and add locale detection, maybe we could get away with just backticks, or we could try using `Process.spawn`, now that we only support ruby versions that include it.

### PR DESCRIPTION
**Pull request by lamont-granquist**
fixes #4

### CODE REVIEW

**Comment by lamont-granquist** [comment]
removes the circular dep back into chef.

**Comment by danielsdeleo** [comment]
:+1:

**Comment by thommay** [comment]
:+1:

**Comment by ranjib** [comment]
shellout! Would raise exception on failure. This will suppress failures, is that intended?

**Comment by lamont-granquist** [comment]
I didn't consciously intend it, but I think that actually fixes a bug where `locale -a` may not exist and we actually don't want to raise an error there.

**Comment by lamont-granquist** [comment]
oh no but i see we've got a rescue clause for that....

**Comment by ranjib** [comment]
:+1:

**Pull request merged**
